### ISSUE TITLE
Using Albedo in browser (not server-side)

### ISSUE THREAD

**Issue by ftppro** [stellar-expert/albedo#56]
Please provide code which demonstrates how to use Albedo in the browser, and not server-side.

Your documentation indicates the following:
---------------------------------
Alternatively, you can import the UMD build in the browser directly from UNPKG:
<script src="https://unpkg.com/@albedo-link/intent/lib/albedo.intent.js"></script>
---------------------------------

Please provide some code to show how I can use the publicKey function (from the albedo object that is provided in albedo.intent.js).

**Comment by orbitlens** [comment]
Albedo is a purely client-side app, you can't run it on NodeJS or a headless browser since it relies on browser-specific APIs. All the code you see in the Demo section, works only in a browser context. 

[This example](https://albedo.link/playground?section=public_key) demonstrates how you can use the `publicKey` intent.

**Comment by ftppro** [comment]
The example did not show how I can access the publicKey function (from the albedo object that is provided in albedo.intent.js).
Please provide some javascript code to show how this can be done.
