### ISSUE TITLE
Get public key on testnet

### ISSUE THREAD

**Issue by quietbits** [stellar-expert/albedo#74]
Hello! :wave: I'd like to use Albedo on the Stellar test network, but I can't find a way how to fetch account info (get a public key) on testnet using `@albedo-link/intent`. I looked at the [documentation](https://albedo.link/playground?section=public_key&output=script) and this repo but no luck (other methods have an option to set the network). Could you please point me in the right direction if I'm missing something? We'd like to add this to the Account Viewer. Thank you!

**Comment by orbitlens** [comment]
Hello Iveta,

An account public key doesn't depend on the selected network since it is generated using ED25519 key derevation algorithm. A pubkey will be identical for both pubnet and testnet.

You are right regarding the interface issues. It may be quite confusing from the user's perspective that public key requested for testnet shows "public" network in the intent confirmation interface. We'll remove the network info row from the interface for this particular network in the upcoming release.

**Comment by orbitlens** [comment]
> We'll remove the network info row from the interface for this particular intent in the upcoming release. 

Done ✅
